robocasa_human_posttrain:
  dataset_names:
  - single_panda_gripper.CloseDoubleDoor
  - single_panda_gripper.CloseDrawer
  - single_panda_gripper.CloseSingleDoor
  - single_panda_gripper.CoffeePressButton
  - single_panda_gripper.CoffeeServeMug
  - single_panda_gripper.CoffeeSetupMug
  - single_panda_gripper.OpenDoubleDoor
  - single_panda_gripper.OpenDrawer
  - single_panda_gripper.OpenSingleDoor
  - single_panda_gripper.PnPCabToCounter
  - single_panda_gripper.PnPCounterToCab
  - single_panda_gripper.PnPCounterToMicrowave
  - single_panda_gripper.PnPCounterToSink
  - single_panda_gripper.PnPCounterToStove
  - single_panda_gripper.PnPMicrowaveToCounter
  - single_panda_gripper.PnPSinkToCounter
  - single_panda_gripper.PnPStoveToCounter
  - single_panda_gripper.TurnOffMicrowave
  - single_panda_gripper.TurnOffSinkFaucet
  - single_panda_gripper.TurnOffStove
  - single_panda_gripper.TurnOnMicrowave
  - single_panda_gripper.TurnOnSinkFaucet
  - single_panda_gripper.TurnOnStove
  - single_panda_gripper.TurnSinkSpout
  data_config_names:
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  embodiment_tags: 
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  sampling_strategy: "step" # 'step' or 'trajectory'
  video_backend: "torchvision_av"
  vit_transform_args:
    type: "beingh"
    normalize_type: "imagenet"
    use_color_jitter: true
  frame_step_size: 
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  num_used_episodes_per_task:
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  num_used_episodes_per_dataset:
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  num_used_frames_per_dataset:
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  weight: 1
