uni_posttrain:
  dataset_names:
  # Libero
  - libero_spatial
  - libero_object
  - libero_goal
  - libero_10

  # Robocasa
  - single_panda_gripper.CloseDoubleDoor
  - single_panda_gripper.CloseDrawer
  - single_panda_gripper.CloseSingleDoor
  - single_panda_gripper.CoffeePressButton
  - single_panda_gripper.CoffeeServeMug
  - single_panda_gripper.CoffeeSetupMug
  - single_panda_gripper.OpenDoubleDoor
  - single_panda_gripper.OpenDrawer
  - single_panda_gripper.OpenSingleDoor
  - single_panda_gripper.PnPCabToCounter
  - single_panda_gripper.PnPCounterToCab
  - single_panda_gripper.PnPCounterToMicrowave
  - single_panda_gripper.PnPCounterToSink
  - single_panda_gripper.PnPCounterToStove
  - single_panda_gripper.PnPMicrowaveToCounter
  - single_panda_gripper.PnPSinkToCounter
  - single_panda_gripper.PnPStoveToCounter
  - single_panda_gripper.TurnOffMicrowave
  - single_panda_gripper.TurnOffSinkFaucet
  - single_panda_gripper.TurnOffStove
  - single_panda_gripper.TurnOnMicrowave
  - single_panda_gripper.TurnOnSinkFaucet
  - single_panda_gripper.TurnOnStove
  - single_panda_gripper.TurnSinkSpout

  data_config_names:
  - "libero_nonorm"
  - "libero_nonorm"
  - "libero_nonorm"
  - "libero_nonorm"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"
  - "robocasa_human"

  embodiment_tags:
  - "libero"
  - "libero"
  - "libero"
  - "libero"
  - "robocasa"
  - "robocasa"
  - "robocasa"
  - "robocasa"
  - "robocasa"
  - "robocasa"
  - "robocasa"
  - "robocasa"
  - "robocasa"
  - "robocasa"
  - "robocasa"
  - "robocasa"
  - "robocasa"
  - "robocasa"
  - "robocasa"
  - "robocasa"
  - "robocasa"
  - "robocasa"
  - "robocasa"
  - "robocasa"
  - "robocasa"
  - "robocasa"
  - "robocasa"
  - "robocasa"

  sampling_strategy: "step"    # 'step' or 'trajectory'
  video_backend: "torchvision_av"
  stats_level: "auto"

  vit_transform_args:
    type: "beingh"
    pad2square: false
    use_thumbnail: false
    dynamic_image_size: false
    min_dynamic_patch: 1
    max_dynamic_patch: 12
    min_num_frame: 8
    max_num_frame: 32
    normalize_type: "imagenet"
    min_image_size: 256
    max_image_size: 256
    image_stride: 14
    use_dynamic_size: false
    use_color_jitter: true
    use_coarse_dropout: false

  frame_step_size:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1

  num_used_episodes_per_task:
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1

  num_used_episodes_per_dataset:
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1

  num_used_frames_per_dataset:
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1

  weight: 1
